linters:
  disable-all: true
  enable:
    - govet
    - revive
    - staticcheck
    - gosimple
    - gocritic

linters-settings:
  revive:
    rules:
      # Enforce no magic numbers in config structs
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
          - maxLitCount: "2"
            allowStrs: '""'
            allowInts: "0,1,2"
            ignoreFuncs: "make,len,cap"
  
  gocritic:
    enabled-checks:
      - dupArg
      - dupCase
      - dupSubExpr

# Custom forbidden patterns - enforced via forbidigo when available
# For now, use scripts/check-hardcodes.ps1 in CI

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - all
    - path: defaults\.go$
      linters:
        - revive
    - path: duration\.go$
      linters:
        - revive
  
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0
