package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/waftester/waftester/pkg/ui"
)

func printUsage() {
	// Direct all output to stderr (same stream as banner) to prevent
	// interleaving. fmt.Println uses os.Stdout internally, so redirecting
	// it ensures banner art and help text don't race on the terminal.
	origStdout := os.Stdout
	os.Stdout = os.Stderr
	defer func() { os.Stdout = origStdout }()

	ui.PrintBanner()

	// Adaptive workflow overview
	fmt.Println(ui.SectionStyle.Render("ADAPTIVE WAF TESTING"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("The Smart Workflow (recommended):"))
	fmt.Println()
	fmt.Printf("    %s  Crawl target, find attack surface\n", ui.ConfigValueStyle.Render("1. discover"))
	fmt.Printf("    %s  Generate prioritized test plan based on what was found\n", ui.ConfigValueStyle.Render("2. learn   "))
	fmt.Printf("    %s  Execute targeted tests using the plan\n", ui.ConfigValueStyle.Render("3. run     "))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Quick Example:"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester discover -u https://auth.example.com"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester learn -discovery discovery.json"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -plan testplan.json"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Multi-Target Example:"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester probe -u target1.com,target2.com -c 50"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester scan -l targets.txt -types sqli,xss"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("cat urls.txt | waf-tester probe -stdin"))
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("COMMANDS"))
	fmt.Println()
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("auto    "), ui.SanitizeString("🚀 SUPERPOWER - Full automated scan (discover"+ui.Icon("→", "->")+"analyze JS"+ui.Icon("→", "->")+"learn"+ui.Icon("→", "->")+"run"+ui.Icon("→", "->")+"report)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: superpower, sp"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("assess  "), ui.SanitizeString("🏢 Enterprise WAF assessment with quantitative metrics (F1, precision, MCC)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: assessment, benchmark"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("discover"), "Crawl target, find endpoints from robots/sitemap/JS/Wayback")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("learn   "), "Analyze discovery "+ui.Icon("→", "->")+" generate targeted test plan")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("run     "), "Execute tests (standalone or using test plan from learn)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("scan    "), "Deep vulnerability scanning (SQLi, XSS, SSRF, OAuth, etc.)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("mutate  "), ui.SanitizeString("🆕 Mutation engine - test with all encoding/location/evasion combos"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("bypass  "), ui.SanitizeString("🆕 WAF bypass finder - hunt for bypasses using full mutation matrix"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("fp      "), ui.SanitizeString("🆕 False positive testing with Leipzig corpus (go-ftw style)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: falsepositive, false-positive"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("vendor  "), ui.SanitizeString("🆕 Vendor-specific WAF detection with bypass hints (GoTestWAF style)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: waf-detect, detect-waf"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("tampers "), ui.SanitizeString("🆕 Tamper scripts (70+ sqlmap-compatible transformations)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("protocol"), ui.SanitizeString("🆕 Enterprise protocol detection (gRPC, SOAP, GraphQL, WCF)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: proto"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("fuzz    "), "Directory/content fuzzing with FUZZ keyword (like ffuf)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("probe   "), "Protocol probing (TLS, HTTP/2, headers, WAF/CDN detection)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("crawl   "), "Advanced web crawler with scope control")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("analyze "), "JavaScript analysis (URLs, methods, secrets, DOM sinks)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("validate"), "Check payload files for schema errors")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("validate-templates"), "Check nuclei YAML templates for structure errors")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("update  "), "Fetch latest payloads from OWASP sources")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Advanced Testing:"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("smuggle "), "HTTP request smuggling detection")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("race    "), "Race condition testing")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("headless"), "Headless browser testing (Chrome/Chromium)")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("workflow"), "Execute multi-step test workflows")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("API & Protocol Testing:"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("template"), ui.SanitizeString("🆕 Run Nuclei-compatible YAML templates"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: templates, nuclei"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("grpc    "), ui.SanitizeString("🆕 gRPC service testing via reflection API"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: grpc-test"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("soap    "), ui.SanitizeString("🆕 SOAP/WSDL testing and fuzzing"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: wsdl"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("openapi "), ui.SanitizeString("🆕 OpenAPI/Swagger specification fuzzing"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: openapi-fuzz, swagger"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("cicd    "), ui.SanitizeString("🆕 Generate CI/CD pipeline configurations"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: ci-cd, pipeline"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("plugin  "), ui.SanitizeString("🆕 Plugin management (list, load, run)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: plugins"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("cloud   "), ui.SanitizeString("🆕 Cloud resource discovery (AWS/Azure/GCP)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: cloud-discover"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Reporting:"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("report  "), "Enterprise HTML report generator")
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Aliases: html-report, enterprise-report"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Integration:"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("mcp     "), ui.SanitizeString("🆕 MCP server for AI assistant integration (Claude, VS Code, etc.)"))
	fmt.Printf("  %s  %s\n", ui.StatValueStyle.Render("        "), ui.SanitizeString("  Alias: mcp-server"))
	fmt.Println()

	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Template Library:"))
	fmt.Printf("  %s  Use --policy, --overrides, --template-config with bundled templates\n", "        ")
	fmt.Printf("  %s  Run 'waf-tester docs templates' for full template documentation\n", "        ")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🧠 SMART MODE (--smart)")))
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("WAF-Aware Testing with 197+ Vendor Signatures"))
	fmt.Println()
	fmt.Println("    Smart mode automatically detects the WAF vendor and optimizes testing:")
	fmt.Println()
	fmt.Println("    1. WAF Detection     - Identifies WAF from 197+ vendor signatures (exceeds wafw00f!)")
	fmt.Println("    2. Rate Optimization - Adjusts rate limit to avoid triggering rate blocks")
	fmt.Println("    3. Encoder Priority  - Prioritizes encoders known to bypass that specific WAF")
	fmt.Println("    4. Evasion Selection - Enables evasion techniques effective against that WAF")
	fmt.Println("    5. Bypass Hints      - Shows specific bypass tips for the detected WAF")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Supported WAF Vendors (197 signatures):"))
	fmt.Println("    Cloud: Cloudflare, AWS WAF, Azure WAF, GCP Cloud Armor, Akamai...")
	fmt.Println("    Enterprise: Imperva, F5 BIG-IP, Fortinet, Barracuda, Citrix...")
	fmt.Println("    Software: ModSecurity, NAXSI, Shadow Daemon, lua-resty-waf...")
	fmt.Println("    CDN: Fastly, StackPath, KeyCDN, CDNetworks, ChinaCache...")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Smart Mode Options:"))
	fmt.Println("    --smart              Enable WAF-aware testing")
	fmt.Println("    --smart-mode=MODE    Optimization level: quick, standard, full, bypass, stealth")
	fmt.Println("    --smart-verbose      Show detailed WAF detection and optimization info")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Example:"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester bypass -u https://target.com --smart"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester auto -u https://target.com --smart --smart-mode=full"))
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("DISCOVER COMMAND"))
	fmt.Println()
	fmt.Println("  Automatically finds endpoints and attack surface using multiple techniques:")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Discovery Sources:"))
	fmt.Println("    robots.txt      - Parses Allow/Disallow rules, finds hidden paths")
	fmt.Println("    sitemap.xml     - Checks 9 common paths (sitemap.xml, sitemap_index.xml, ...)")
	fmt.Println("    JavaScript      - Deep JS analysis: URLs, secrets, DOM sinks, HTTP method inference")
	fmt.Println("    Wayback Machine - Historical URLs from web.archive.org (may reveal old endpoints)")
	fmt.Println("    HTML Forms      - Finds login forms, file uploads, API endpoints")
	fmt.Println("    Service Presets - Known endpoints for wordpress, drupal, nextjs, flask, django")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("JavaScript Analysis Features:"))
	fmt.Println("    " + ui.Icon("•", "-") + " Extracts API endpoints from fetch(), axios(), jQuery.ajax(), XMLHttpRequest")
	fmt.Println("    " + ui.Icon("•", "-") + " Infers HTTP methods (POST/PUT/DELETE) from URL patterns and code context")
	fmt.Println("    " + ui.Icon("•", "-") + " Detects secrets: API keys, tokens, credentials (AWS, Google, GitHub, Stripe, etc.)")
	fmt.Println("    " + ui.Icon("•", "-") + " Finds DOM XSS sinks: innerHTML, document.write, eval, etc.")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("INPUT (multiple targets):"))
	fmt.Println("    -u, -target <url> Target URL(s) - comma-separated or repeated")
	fmt.Println("    -l <file>         File containing target URLs (one per line)")
	fmt.Println("    -stdin            Read targets from stdin")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Options:"))
	fmt.Println("    -service <name>   Use known endpoint patterns (wordpress|drupal|nextjs|flask|django)")
	fmt.Println("    -output <file>    Save results to file (default: discovery.json)")
	fmt.Println("    -concurrency <n>  Parallel workers (default: 10)")
	fmt.Println("    -depth <n>        Max crawl depth (default: 3)")
	fmt.Println("    -timeout <sec>    HTTP timeout in seconds (default: 10)")
	fmt.Println("    -skip-verify      Skip TLS verification (self-signed certs)")
	fmt.Println("    -verbose          Show detailed discovery output")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Output:"))
	fmt.Println("    discovery.json - List of endpoints, attack surface analysis, WAF detection")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("LEARN COMMAND"))
	fmt.Println()
	fmt.Println("  Analyzes discovery results and generates a targeted test plan:")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("What it does:"))
	fmt.Println("    " + ui.Icon("•", "-") + " Maps endpoints to relevant attack categories (auth endpoints " + ui.Icon("→", "->") + " auth attacks)")
	fmt.Println("    " + ui.Icon("•", "-") + " Prioritizes: P1 (auth/injection) " + ui.Icon("→", "->") + " P5 (fuzz testing)")
	fmt.Println("    " + ui.Icon("•", "-") + " Calculates optimal concurrency and rate limits")
	fmt.Println("    " + ui.Icon("•", "-") + " Generates custom payloads for specific endpoints")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("INPUT (multiple targets):"))
	fmt.Println("    -u, -target <url> Target URL(s) - comma-separated or repeated")
	fmt.Println("    -l <file>         File containing target URLs (one per line)")
	fmt.Println("    -stdin            Read targets from stdin")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Options:"))
	fmt.Println("    -discovery <file>  Discovery JSON from 'discover' command")
	fmt.Println("    -payloads <dir>    Payload directory (default: ./payloads)")
	fmt.Println("    -output <file>     Save test plan (default: testplan.json)")
	fmt.Println("    -custom-payloads   Also export custom payloads to file")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("Output:"))
	fmt.Println("    testplan.json - Target, categories, priorities, recommended flags")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("RUN COMMAND"))
	fmt.Println()
	fmt.Println("  Executes WAF security tests. Use with -plan for targeted testing,")
	fmt.Println("  or standalone with -target for manual control.")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("INPUT (multiple targets):"))
	fmt.Println("    -u, -target <url> Target URL(s) - comma-separated or repeated")
	fmt.Println("    -l <file>         File containing target URLs (one per line)")
	fmt.Println("    -plan <file>      Test plan from 'learn' command")
	fmt.Println("    -stdin            Read targets from stdin (for piping)")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("EXECUTION:"))
	fmt.Println("    -c <n>                 Concurrent workers (default: 25)")
	fmt.Println("    -rl, -rate-limit <n>   Requests per second (default: 150)")
	fmt.Println("    -timeout <sec>         HTTP timeout (default: 5)")
	fmt.Println("    -retries <n>           Retry count on failure (default: 1)")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("PAYLOADS:"))
	fmt.Println("    -p, -payloads <dir>    Payload directory (default: ./payloads)")
	fmt.Println("    -category <name>       Filter: xss, injection, auth, traversal, etc")
	fmt.Println("    -severity <level>      Filter: Critical, High, Medium, Low")
	fmt.Println("    -dry-run               List tests without executing")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("MUTATION (WAF bypass):"))
	fmt.Println("    -m, -mutation <mode>   Mutation mode: none, quick, standard, full")
	fmt.Println("    -encoders <list>       Comma-separated encoders (url,double_url,html_hex)")
	fmt.Println("    -locations <list>      Comma-separated locations (query_param,post_json)")
	fmt.Println("    -evasions <list>       Comma-separated evasions (case_swap,sql_comment)")
	fmt.Println("    -chain                 Enable chained mutations (encoder " + ui.Icon("→", "->") + " evasion)")
	fmt.Println("    -max-chain <n>         Maximum chain depth (default: 2)")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("MATCHERS (what to report):"))
	fmt.Println("    -mc <codes>            Match status codes (e.g., 200,403,500)")
	fmt.Println("    -ms <size>             Match response size")
	fmt.Println("    -mw <count>            Match response word count")
	fmt.Println("    -ml <count>            Match response line count")
	fmt.Println("    -mr <regex>            Match response body regex")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("FILTERS (what to hide):"))
	fmt.Println("    -fc <codes>            Filter status codes (e.g., 404,500)")
	fmt.Println("    -fs <size>             Filter response size")
	fmt.Println("    -fw <count>            Filter response word count")
	fmt.Println("    -fl <count>            Filter response line count")
	fmt.Println("    -fr <regex>            Filter response body regex")
	fmt.Println("    -ac                    Auto-calibrate (detect baseline responses)")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("OUTPUT:"))
	fmt.Println("    -o <file>              Output file path")
	fmt.Println("    -format <type>         Format: console, json, jsonl, sarif, csv, md, html")
	fmt.Println("    -j, -jsonl             JSONL output (one JSON per line)")
	fmt.Println("    -v, -verbose           Verbose output")
	fmt.Println("    -s, -silent            Silent mode - no progress")
	fmt.Println("    -nc, -no-color         Disable colored output")
	fmt.Println("    -sr, -store-response   Store HTTP responses to directory")
	fmt.Println("    -srd <dir>             Directory for stored responses")
	fmt.Println("    -stats                 Show statistics during execution")
	fmt.Println("    -noninteractive        Disable ENTER-to-pause feature")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("NETWORK:"))
	fmt.Println("    -x, -proxy <url>       HTTP/SOCKS5 proxy")
	fmt.Println("    -k, -skip-verify       Skip TLS verification")
	fmt.Println("    -replay-proxy <url>    Secondary proxy for matched requests (Burp/ZAP)")
	fmt.Println("    -sni <host>            TLS SNI hostname override")
	fmt.Println("    -burp                  Shortcut: --proxy http://127.0.0.1:8080 --skip-verify")
	fmt.Println("    -zap                   Shortcut: --proxy http://127.0.0.1:8081 --skip-verify")
	fmt.Println("    -detect                Enable connection drop/silent ban detection (default: true)")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("REALISTIC MODE (advanced):"))
	fmt.Println("    -R, -realistic         Use realistic browser-like requests & smart block detection")
	fmt.Println("                           Includes: rotating User-Agents, realistic headers,")
	fmt.Println("                           multi-location injection, intelligent WAF block detection")
	fmt.Println()
	fmt.Printf("  %s\n", ui.SubtitleStyle.Render("EXAMPLES:"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -plan testplan.json"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -u https://example.com -c 50 -rl 200"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -u https://example.com -mc 403 -j -o results.jsonl"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -u https://example.com -format html -o report.html"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("waf-tester run -u https://example.com -ts -format csv -o results.csv"))
	fmt.Printf("    %s\n", ui.ConfigValueStyle.Render("echo https://target.com | waf-tester run -stdin -s"))
	fmt.Println()

	ui.PrintHelp("Run \"waf-tester <command> -h\" for command-specific help")
	ui.PrintHelp("Run \"waf-tester docs\" for comprehensive documentation")
	fmt.Println()
}

// printDetailedDocs prints comprehensive documentation for all features
func printDetailedDocs() {
	// Direct all output to stderr (same stream as banner) to prevent interleaving
	origStdout := os.Stdout
	os.Stdout = os.Stderr
	defer func() { os.Stdout = origStdout }()

	ui.PrintBanner()

	// Check if a specific topic was requested
	topic := ""
	if len(os.Args) > 2 {
		topic = strings.ToLower(os.Args[2])
	}

	switch topic {
	case "discover", "discovery":
		printDocsDiscover()
	case "learn", "learning":
		printDocsLearn()
	case "run", "execute", "test":
		printDocsRun()
	case "auto", "superpower":
		printDocsAuto()
	case "assess", "assessment", "benchmark", "enterprise":
		printDocsAssess()
	case "scan", "scanning":
		printDocsScan()
	case "mutate", "mutation", "mutations":
		printDocsMutation()
	case "bypass", "bypasses":
		printDocsBypass()
	case "fuzz", "fuzzing":
		printDocsFuzz()
	case "probe", "probing":
		printDocsProbe()
	case "crawl", "crawler":
		printDocsCrawl()
	case "analyze", "js", "javascript":
		printDocsAnalyze()
	case "payloads", "payload":
		printDocsPayloads()
	case "categories", "category":
		printDocsCategories()
	case "output", "formats", "format":
		printDocsOutput()
	case "examples", "example":
		printDocsExamples()
	case "mcp", "mcp-server":
		printDocsMcp()
	case "workflow", "workflows":
		printDocsWorkflow()
	case "template", "templates":
		printDocsTemplates()
	default:
		printDocsIndex()
	}
}

func printDocsIndex() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📚 WAF-TESTER COMPREHENSIVE DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  Welcome to waf-tester - the adaptive WAF security testing toolkit.")
	fmt.Println("  This tool helps you discover vulnerabilities and test WAF effectiveness.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("AVAILABLE DOCUMENTATION TOPICS"))
	fmt.Println()
	fmt.Println("  Run: waf-tester docs <topic>")
	fmt.Println()
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("discover"), "Target discovery and attack surface mapping")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("learn"), "Intelligent test plan generation")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("run"), "Test execution and result handling")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("auto"), "Full automated scanning workflow")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("assess"), "Enterprise assessment with quantitative metrics")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("scan"), "Deep vulnerability scanning")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("mutate"), "Payload mutation and encoding")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("bypass"), "WAF bypass techniques")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("fuzz"), "Directory and content fuzzing")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("probe"), "Protocol and WAF detection")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("crawl"), "Advanced web crawling")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("analyze"), "JavaScript analysis")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("payloads"), "Payload structure and formats")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("categories"), "Attack categories explained")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("output"), "Output formats and reporting")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("examples"), "Real-world usage examples")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("workflow"), "Recommended testing workflows")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("templates"), "Template library (nuclei, workflows, policies, overrides)")
	fmt.Printf("  %-15s %s\n", ui.StatValueStyle.Render("mcp"), "MCP server for AI assistant integration")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("QUICK START GUIDE"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("1. Basic WAF Test (single target):"))
	fmt.Println("     waf-tester run -u https://example.com -c 25")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("2. Smart Adaptive Testing (recommended):"))
	fmt.Println("     waf-tester discover -u https://target.com -output discovery.json")
	fmt.Println("     waf-tester learn -discovery discovery.json -output testplan.json")
	fmt.Println("     waf-tester run -plan testplan.json -o results.json")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("3. Full Automated Scan (one command):"))
	fmt.Println("     waf-tester auto -u https://target.com -service myapp")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("4. WAF Bypass Hunting:"))
	fmt.Println("     waf-tester bypass -u https://target.com -category sqli -mutation full")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("CORE CONCEPTS"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Adaptive Testing:"))
	fmt.Println("    Unlike traditional scanners that blindly throw payloads, waf-tester adapts:")
	fmt.Println("    " + ui.Icon("•", "-") + " Discovers your target's attack surface first")
	fmt.Println("    " + ui.Icon("•", "-") + " Learns which tests are relevant for what was found")
	fmt.Println("    " + ui.Icon("•", "-") + " Prioritizes high-value tests (auth, injection) over noise")
	fmt.Println("    " + ui.Icon("•", "-") + " Auto-calibrates to filter out false positives")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Mutation Engine:"))
	fmt.Println("    Payloads are automatically mutated to bypass WAF filters:")
	fmt.Println("    " + ui.Icon("•", "-") + " Encoders: URL, Double-URL, HTML, Unicode, Base64, etc.")
	fmt.Println("    " + ui.Icon("•", "-") + " Locations: Query params, POST body, JSON, headers, cookies")
	fmt.Println("    " + ui.Icon("•", "-") + " Evasions: Case swapping, SQL comments, null bytes, etc.")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Realistic Mode:"))
	fmt.Println("    Makes requests look like real browser traffic:")
	fmt.Println("    " + ui.Icon("•", "-") + " Rotating User-Agents (Chrome, Firefox, Safari)")
	fmt.Println("    " + ui.Icon("•", "-") + " Real browser headers (Accept, Accept-Language, etc.)")
	fmt.Println("    " + ui.Icon("•", "-") + " Intelligent WAF block detection")
	fmt.Println()
}

func printDocsDiscover() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📡 DISCOVER COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The discover command maps your target's attack surface by gathering")
	fmt.Println("  endpoints from multiple sources. This is the foundation for smart testing.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("DISCOVERY SOURCES EXPLAINED"))
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("1. robots.txt Parsing"))
	fmt.Println("     What: Parses /robots.txt for Allow and Disallow rules")
	fmt.Println("     Why:  Often reveals hidden admin panels, API paths, staging areas")
	fmt.Println("     Example findings: /admin/, /api/v2/, /staging/, /.git/")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("2. Sitemap Discovery"))
	fmt.Println("     What: Checks 9 common sitemap locations")
	fmt.Println("     Checks: sitemap.xml, sitemap_index.xml, sitemap-index.xml,")
	fmt.Println("             sitemaps.xml, sitemap1.xml, post-sitemap.xml,")
	fmt.Println("             page-sitemap.xml, sitemap.xml.gz, sitemap_index.xml.gz")
	fmt.Println("     Why:  Full URL listing of public pages, reveals URL structure")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("3. JavaScript Analysis (Deep)"))
	fmt.Println("     What: Downloads and parses all .js files for:")
	fmt.Println("     " + ui.Icon("•", "-") + " API endpoints (fetch, axios, jQuery.ajax, XMLHttpRequest)")
	fmt.Println("     " + ui.Icon("•", "-") + " HTTP methods inferred from URL patterns (/login " + ui.Icon("→", "->") + " POST)")
	fmt.Println("     " + ui.Icon("•", "-") + " Hardcoded secrets (API keys, tokens, credentials)")
	fmt.Println("     " + ui.Icon("•", "-") + " DOM XSS sinks (innerHTML, document.write, eval)")
	fmt.Println("     " + ui.Icon("•", "-") + " AWS/Google/GitHub/Stripe/Twilio API keys")
	fmt.Println("     Why:  Modern SPAs have all API endpoints in JavaScript")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("4. Wayback Machine"))
	fmt.Println("     What: Queries web.archive.org for historical URLs")
	fmt.Println("     Why:  Reveals endpoints that may still exist but are unlisted")
	fmt.Println("     Finds: Old API versions, removed pages, debug endpoints")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("5. HTML Form Analysis"))
	fmt.Println("     What: Parses HTML for <form> elements")
	fmt.Println("     Finds: Login forms, file uploads, search forms, contact forms")
	fmt.Println("     Why:  Forms are primary injection points")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("6. Service Presets"))
	fmt.Println("     What: Pre-defined endpoint patterns for known applications")
	fmt.Println("     Supported: wordpress, drupal, nextjs, flask, django")
	fmt.Println("     Why:  Skip discovery for known app types")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FLAGS AND OPTIONS"))
	fmt.Println()
	fmt.Println("  -u, -target <url>    Target URL (required)")
	fmt.Println("                       Can be repeated: -u site1.com -u site2.com")
	fmt.Println("                       Comma-separated: -u site1.com,site2.com")
	fmt.Println()
	fmt.Println("  -l <file>            File with target URLs (one per line)")
	fmt.Println()
	fmt.Println("  -service <name>      Use preset endpoints for known apps")
	fmt.Println("                       Options: wordpress, drupal, nextjs, flask, django")
	fmt.Println()
	fmt.Println("  -output <file>       Output file (default: discovery.json)")
	fmt.Println()
	fmt.Println("  -depth <n>           Crawl depth for HTML parsing (default: 3)")
	fmt.Println("                       Higher = more thorough but slower")
	fmt.Println()
	fmt.Println("  -concurrency <n>     Parallel discovery workers (default: 10)")
	fmt.Println()
	fmt.Println("  -timeout <sec>       HTTP timeout per request (default: 10)")
	fmt.Println()
	fmt.Println("  -skip-verify         Skip TLS certificate verification")
	fmt.Println("                       Use for self-signed certs in testing environments")
	fmt.Println()
	fmt.Println("  -verbose             Show detailed discovery progress")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OUTPUT FORMAT"))
	fmt.Println()
	fmt.Println("  The discovery.json contains:")
	fmt.Println("  {")
	fmt.Println("    \"target\": \"https://example.com\",")
	fmt.Println("    \"endpoints\": [")
	fmt.Println("      {\"path\": \"/api/users\", \"method\": \"GET\", \"source\": \"js\"},")
	fmt.Println("      {\"path\": \"/login\", \"method\": \"POST\", \"source\": \"form\"}")
	fmt.Println("    ],")
	fmt.Println("    \"js_files\": [\"/app.js\", \"/vendor.js\"],")
	fmt.Println("    \"secrets\": [{\"type\": \"aws_key\", \"value\": \"AKIA...\"}],")
	fmt.Println("    \"waf_detected\": \"cloudflare\"")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Basic discovery")
	fmt.Println("  waf-tester discover -u https://target.com")
	fmt.Println()
	fmt.Println("  # With service preset")
	fmt.Println("  waf-tester discover -u https://auth.example.com -service authentik")
	fmt.Println()
	fmt.Println("  # Deep discovery with verbose output")
	fmt.Println("  waf-tester discover -u https://target.com -depth 5 -verbose")
	fmt.Println()
	fmt.Println("  # Multiple targets")
	fmt.Println("  waf-tester discover -l targets.txt -output all-discovery.json")
	fmt.Println()
}

func printDocsLearn() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🧠 LEARN COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The learn command analyzes discovery results and generates an")
	fmt.Println("  intelligent, prioritized test plan tailored to your target.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("HOW IT WORKS"))
	fmt.Println()
	fmt.Println("  1. " + ui.SubtitleStyle.Render("Endpoint Analysis"))
	fmt.Println("     " + ui.Icon("•", "-") + " Classifies endpoints by type (auth, API, admin, static)")
	fmt.Println("     " + ui.Icon("•", "-") + " Identifies high-value targets (login, password reset, file upload)")
	fmt.Println("     " + ui.Icon("•", "-") + " Maps parameters that accept user input")
	fmt.Println()
	fmt.Println("  2. " + ui.SubtitleStyle.Render("Category Mapping"))
	fmt.Println("     " + ui.Icon("•", "-") + " /login, /auth " + ui.Icon("→", "->") + " Authentication attacks (brute force, credential stuffing)")
	fmt.Println("     " + ui.Icon("•", "-") + " /api/*, /search " + ui.Icon("→", "->") + " Injection attacks (SQLi, NoSQLi, XSS)")
	fmt.Println("     " + ui.Icon("•", "-") + " /upload, /import " + ui.Icon("→", "->") + " File upload attacks")
	fmt.Println("     " + ui.Icon("•", "-") + " /admin, /dashboard " + ui.Icon("→", "->") + " Privilege escalation")
	fmt.Println()
	fmt.Println("  3. " + ui.SubtitleStyle.Render("Priority Assignment"))
	fmt.Println("     P1 (Critical): Authentication, SQL injection, command injection")
	fmt.Println("     P2 (High):     XSS, SSRF, file upload, path traversal")
	fmt.Println("     P3 (Medium):   CSRF, open redirect, information disclosure")
	fmt.Println("     P4 (Low):      Verbose errors, missing headers")
	fmt.Println("     P5 (Info):     Fuzzing, enumeration")
	fmt.Println()
	fmt.Println("  4. " + ui.SubtitleStyle.Render("Rate Optimization"))
	fmt.Println("     " + ui.Icon("•", "-") + " Calculates safe request rate based on WAF detection")
	fmt.Println("     " + ui.Icon("•", "-") + " Adjusts concurrency for target capacity")
	fmt.Println("     " + ui.Icon("•", "-") + " Generates recommended execution flags")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FLAGS AND OPTIONS"))
	fmt.Println()
	fmt.Println("  -discovery <file>    Input: discovery.json from 'discover' command (required)")
	fmt.Println()
	fmt.Println("  -u, -target <url>    Target URL (uses discovery data if not specified)")
	fmt.Println()
	fmt.Println("  -payloads <dir>      Payload directory (default: ./payloads)")
	fmt.Println("                       Must contain category subdirectories with JSON files")
	fmt.Println()
	fmt.Println("  -output <file>       Output test plan file (default: testplan.json)")
	fmt.Println()
	fmt.Println("  -custom-payloads     Also generate custom payloads file")
	fmt.Println("                       Creates targeted payloads based on discovered patterns")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("TEST PLAN FORMAT"))
	fmt.Println()
	fmt.Println("  {")
	fmt.Println("    \"target\": \"https://example.com\",")
	fmt.Println("    \"generated_at\": \"2026-01-27T10:30:00Z\",")
	fmt.Println("    \"categories\": [\"sqli\", \"xss\", \"auth\"],")
	fmt.Println("    \"priorities\": {\"sqli\": 1, \"xss\": 2, \"auth\": 1},")
	fmt.Println("    \"endpoints\": [{\"path\": \"/api/login\", \"methods\": [\"POST\"]}],")
	fmt.Println("    \"recommended_flags\": {")
	fmt.Println("      \"concurrency\": 25,")
	fmt.Println("      \"rate_limit\": 100,")
	fmt.Println("      \"realistic\": true")
	fmt.Println("    }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Generate test plan from discovery")
	fmt.Println("  waf-tester learn -discovery discovery.json")
	fmt.Println()
	fmt.Println("  # With custom output path")
	fmt.Println("  waf-tester learn -discovery discovery.json -output my-testplan.json")
	fmt.Println()
	fmt.Println("  # Also generate custom payloads")
	fmt.Println("  waf-tester learn -discovery discovery.json -custom-payloads")
	fmt.Println()
}

func printDocsRun() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🚀 RUN COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The run command executes WAF security tests against your target.")
	fmt.Println("  Use with -plan for intelligent testing or standalone for manual control.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXECUTION MODES"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("1. Plan-Based (Recommended)"))
	fmt.Println("     waf-tester run -plan testplan.json")
	fmt.Println("     " + ui.Icon("•", "-") + " Uses test plan from 'learn' command")
	fmt.Println("     " + ui.Icon("•", "-") + " Automatically prioritizes tests")
	fmt.Println("     " + ui.Icon("•", "-") + " Applies recommended settings")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("2. Standalone"))
	fmt.Println("     waf-tester run -u https://target.com -category sqli")
	fmt.Println("     " + ui.Icon("•", "-") + " Manual control over all settings")
	fmt.Println("     " + ui.Icon("•", "-") + " Good for targeted testing of specific categories")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("CONCURRENCY AND RATE LIMITING"))
	fmt.Println()
	fmt.Println("  -c <n>               Concurrent workers (default: 25)")
	fmt.Println("                       Higher = faster but may trigger rate limits")
	fmt.Println("                       Lower = slower but safer")
	fmt.Println()
	fmt.Println("  -rl, -rate-limit <n> Max requests per second (default: 150)")
	fmt.Println("                       Adjust based on target capacity and WAF sensitivity")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Recommended Settings:"))
	fmt.Println("     " + ui.Icon("•", "-") + " Production sites: -c 10 -rl 20 (conservative)")
	fmt.Println("     " + ui.Icon("•", "-") + " Staging/test: -c 50 -rl 200 (aggressive)")
	fmt.Println("     " + ui.Icon("•", "-") + " WAF bypass hunting: -c 5 -rl 10 (stealth)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FILTERING AND MATCHING"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Match (what to report):"))
	fmt.Println("  -mc <codes>          Match status codes: -mc 200,403,500")
	fmt.Println("  -ms <size>           Match response size: -ms 1234")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Filter (what to hide):"))
	fmt.Println("  -fc <codes>          Filter status codes: -fc 404,500")
	fmt.Println("  -fs <size>           Filter response size: -fs 0")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Auto-Calibration:"))
	fmt.Println("  -ac                  Automatically detect and filter baseline responses")
	fmt.Println("                       Sends probe requests to learn normal response patterns")
	fmt.Println("                       Then filters out responses matching the baseline")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OUTPUT OPTIONS"))
	fmt.Println()
	fmt.Println("  -o <file>            Output file path")
	fmt.Println("  -format <type>       Output format:")
	fmt.Println("                       " + ui.Icon("•", "-") + " console - Human-readable terminal output")
	fmt.Println("                       " + ui.Icon("•", "-") + " json    - Single JSON array")
	fmt.Println("                       " + ui.Icon("•", "-") + " jsonl   - JSON Lines (one object per line)")
	fmt.Println("                       " + ui.Icon("•", "-") + " sarif   - SARIF for IDE integration")
	fmt.Println("                       " + ui.Icon("•", "-") + " csv     - Spreadsheet-compatible")
	fmt.Println("                       " + ui.Icon("•", "-") + " md      - Markdown table")
	fmt.Println("                       " + ui.Icon("•", "-") + " html    - Interactive HTML report")
	fmt.Println()
	fmt.Println("  -v, -verbose         Show detailed test output")
	fmt.Println("  -s, -silent          No progress output (for scripting)")
	fmt.Println("  -stats               Show live statistics")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("REALISTIC MODE"))
	fmt.Println()
	fmt.Println("  -R, -realistic       Enable realistic browser simulation")
	fmt.Println()
	fmt.Println("  Features:")
	fmt.Println("  " + ui.Icon("•", "-") + " Rotating User-Agent strings (Chrome, Firefox, Safari, Edge)")
	fmt.Println("  " + ui.Icon("•", "-") + " Realistic Accept headers (text/html, application/json)")
	fmt.Println("  " + ui.Icon("•", "-") + " Accept-Language, Accept-Encoding headers")
	fmt.Println("  " + ui.Icon("•", "-") + " Referer header simulation")
	fmt.Println("  " + ui.Icon("•", "-") + " Multi-location injection (query, body, headers)")
	fmt.Println("  " + ui.Icon("•", "-") + " Intelligent WAF block detection (pattern matching)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Run with test plan")
	fmt.Println("  waf-tester run -plan testplan.json")
	fmt.Println()
	fmt.Println("  # Manual run with specific category")
	fmt.Println("  waf-tester run -u https://target.com -category sqli -c 25")
	fmt.Println()
	fmt.Println("  # Generate HTML report")
	fmt.Println("  waf-tester run -plan testplan.json -format html -o report.html")
	fmt.Println()
	fmt.Println("  # Conservative testing with auto-calibration")
	fmt.Println("  waf-tester run -u https://prod.com -c 10 -rl 20 -ac -realistic")
	fmt.Println()
	fmt.Println("  # Silent mode for scripting")
	fmt.Println("  waf-tester run -plan testplan.json -s -o results.json")
	fmt.Println()
}

func printDocsAuto() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("⚡ AUTO COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The auto command runs a complete security assessment in one command:")
	fmt.Println("  discover " + ui.Icon("→", "->") + " analyze " + ui.Icon("→", "->") + " learn " + ui.Icon("→", "->") + " run " + ui.Icon("→", "->") + " report")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("WHAT IT DOES"))
	fmt.Println()
	fmt.Println("  1. " + ui.SubtitleStyle.Render("Discovery Phase"))
	fmt.Println("     " + ui.Icon("•", "-") + " Crawls target for endpoints")
	fmt.Println("     " + ui.Icon("•", "-") + " Parses robots.txt, sitemap")
	fmt.Println("     " + ui.Icon("•", "-") + " Analyzes JavaScript for API endpoints")
	fmt.Println("     " + ui.Icon("•", "-") + " Queries Wayback Machine")
	fmt.Println()
	fmt.Println("  2. " + ui.SubtitleStyle.Render("Analysis Phase"))
	fmt.Println("     " + ui.Icon("•", "-") + " Deep JavaScript analysis for secrets")
	fmt.Println("     " + ui.Icon("•", "-") + " DOM XSS sink detection")
	fmt.Println("     " + ui.Icon("•", "-") + " WAF fingerprinting")
	fmt.Println()
	fmt.Println("  3. " + ui.SubtitleStyle.Render("Learning Phase"))
	fmt.Println("     " + ui.Icon("•", "-") + " Maps endpoints to attack categories")
	fmt.Println("     " + ui.Icon("•", "-") + " Prioritizes tests")
	fmt.Println("     " + ui.Icon("•", "-") + " Generates optimized test plan")
	fmt.Println()
	fmt.Println("  4. " + ui.SubtitleStyle.Render("Execution Phase"))
	fmt.Println("     " + ui.Icon("•", "-") + " Runs all prioritized tests")
	fmt.Println("     " + ui.Icon("•", "-") + " Auto-calibrates filters")
	fmt.Println("     " + ui.Icon("•", "-") + " Applies mutation if needed")
	fmt.Println()
	fmt.Println("  5. " + ui.SubtitleStyle.Render("Reporting Phase"))
	fmt.Println("     " + ui.Icon("•", "-") + " Generates results in requested format")
	fmt.Println("     " + ui.Icon("•", "-") + " Creates workspace with all artifacts")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FLAGS AND OPTIONS"))
	fmt.Println()
	fmt.Println("  -u, -target <url>    Target URL (required)")
	fmt.Println("  -service <name>      Service name (for workspace organization)")
	fmt.Println("  -c <n>               Concurrency (default: 50)")
	fmt.Println("  -rl <n>              Rate limit (default: 200)")
	fmt.Println("  -depth <n>           Discovery depth (default: 3)")
	fmt.Println("  -output-dir <path>   Custom output directory")
	fmt.Println("  -payloads <dir>      Payload directory")
	fmt.Println("  -j, -json            Output final summary as JSON to stdout")
	fmt.Println("  -stream              Streaming output mode for CI/scripts")
	fmt.Println("  -v                   Verbose output")
	fmt.Println()
	fmt.Println("  Smart Mode:")
	fmt.Println("  --smart              Enable WAF-aware testing (auto-detect WAF)")
	fmt.Println("  --smart-mode <mode>  Optimization level: quick, standard, full, bypass, stealth")
	fmt.Println()
	fmt.Println("  Feature Toggles:")
	fmt.Println("  --assess             Run enterprise assessment (default: true)")
	fmt.Println("  --leaky-paths        Enable sensitive path scanning (default: true)")
	fmt.Println("  --discover-params    Enable parameter discovery (default: true)")
	fmt.Println("  --browser            Enable browser-based scanning (default: true)")
	fmt.Println("  --full-recon         Run unified reconnaissance")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("WORKSPACE STRUCTURE"))
	fmt.Println()
	fmt.Println("  Auto creates a workspace directory:")
	fmt.Println("  workspaces/")
	fmt.Println("  └── example.com/")
	fmt.Println("      └── 2026-01-27_10-30-00/")
	fmt.Println("          ├── discovery.json")
	fmt.Println("          ├── testplan.json")
	fmt.Println("          ├── results.json")
	fmt.Println("          ├── results.html")
	fmt.Println("          └── results.sarif")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Full automated scan")
	fmt.Println("  waf-tester auto -u https://target.com -service myapp")
	fmt.Println()
	fmt.Println("  # Output JSON summary to stdout (for scripting)")
	fmt.Println("  waf-tester auto -u https://target.com --json")
	fmt.Println()
	fmt.Println("  # CI/CD pipeline with JSON output")
	fmt.Println("  waf-tester auto -u https://target.com -j > summary.json")
	fmt.Println()
	fmt.Println("  # Conservative automated scan")
	fmt.Println("  waf-tester auto -u https://prod.com -c 10 -rl 20")
	fmt.Println()
	fmt.Println("  # Smart mode with WAF-aware optimization")
	fmt.Println("  waf-tester auto -u https://target.com --smart")
	fmt.Println()
}

func printDocsAssess() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🏢 ENTERPRISE WAF ASSESSMENT - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The assess command provides comprehensive WAF evaluation with")
	fmt.Println("  quantitative metrics used in academic research and enterprise audits.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("WHAT IT DOES"))
	fmt.Println()
	fmt.Println("  1. Attack Testing   - Tests WAF with curated attack payloads")
	fmt.Println("  2. FP Testing       - Tests with benign corpus (Leipzig, builtin)")
	fmt.Println("  3. Metrics          - Computes precision, recall, F1, MCC, etc.")
	fmt.Println("  4. Grading          - Assigns A+ to F grade with recommendations")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("QUANTITATIVE METRICS"))
	fmt.Println()
	fmt.Println("  Primary Metrics:")
	fmt.Println("    " + ui.Icon("•", "-") + " Detection Rate (TPR/Recall) - % of attacks blocked")
	fmt.Println("    " + ui.Icon("•", "-") + " False Positive Rate (FPR)   - % of legitimate traffic blocked")
	fmt.Println("    " + ui.Icon("•", "-") + " Precision                   - % of blocks that were real attacks")
	fmt.Println("    " + ui.Icon("•", "-") + " Specificity (TNR)           - % of legitimate traffic allowed")
	fmt.Println()
	fmt.Println("  Balanced Metrics:")
	fmt.Println("    " + ui.Icon("•", "-") + " F1 Score            - Harmonic mean of precision & recall")
	fmt.Println("    " + ui.Icon("•", "-") + " F2 Score            - Recall-weighted F-measure")
	fmt.Println("    " + ui.Icon("•", "-") + " MCC                 - Matthews Correlation Coefficient (-1 to +1)")
	fmt.Println("    " + ui.Icon("•", "-") + " Balanced Accuracy   - Average of TPR and TNR")
	fmt.Println()
	fmt.Println("  WAF-Specific Metrics:")
	fmt.Println("    " + ui.Icon("•", "-") + " Bypass Resistance   - Attack detection with evasion techniques")
	fmt.Println("    " + ui.Icon("•", "-") + " Block Consistency   - Variance across attack categories")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FALSE POSITIVE CORPUS"))
	fmt.Println()
	fmt.Println("  -corpus <sources>     Comma-separated corpus sources:")
	fmt.Println()
	fmt.Println("    builtin     130+ curated benign sentences (forms, news, technical)")
	fmt.Println("    leipzig     Leipzig Corpora Collection (downloaded & cached)")
	fmt.Println()
	fmt.Println("  -custom-corpus <file> Your own corpus (JSON array or line-by-line)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OPTIONS"))
	fmt.Println()
	fmt.Println("  -u <url>              Target URL (required)")
	fmt.Println("  -c <n>                Concurrency (default: 25)")
	fmt.Println("  -rate <n>             Rate limit req/sec (default: 100)")
	fmt.Println("  -timeout <n>          Request timeout seconds (default: 10)")
	fmt.Println("  -categories <list>    Attack categories to test (default: all)")
	fmt.Println("  -fp                   Enable FP testing (default: true)")
	fmt.Println("  -detect-waf           Auto-detect WAF vendor (default: true)")
	fmt.Println("  -o <file>             Output results to file")
	fmt.Println("  -format <fmt>         Output format: console, json (default: console)")
	fmt.Println("  -v                    Verbose output")
	fmt.Println("  -k                    Skip TLS verification")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("GRADING SCALE"))
	fmt.Println()
	fmt.Println("    A+   F1 >= 0.95, FPR < 0.01    Exceptional - enterprise ready")
	fmt.Println("    A    F1 >= 0.90, FPR < 0.02    Excellent - production quality")
	fmt.Println("    B+   F1 >= 0.85, FPR < 0.05    Good - minor tuning needed")
	fmt.Println("    B    F1 >= 0.80, FPR < 0.05    Good - some improvements needed")
	fmt.Println("    C    F1 >= 0.70, FPR < 0.10    Acceptable - significant gaps")
	fmt.Println("    D    F1 >= 0.50, FPR < 0.15    Poor - major issues")
	fmt.Println("    F    F1 < 0.50 or FPR >= 0.15  Failing - not production ready")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Basic assessment")
	fmt.Println("  waf-tester assess -u https://example.com")
	fmt.Println()
	fmt.Println("  # Full corpus with JSON output")
	fmt.Println("  waf-tester assess -u https://example.com -corpus builtin,leipzig -o report.json -format json")
	fmt.Println()
	fmt.Println("  # Specific categories")
	fmt.Println("  waf-tester assess -u https://example.com -categories sqli,xss,cmdi")
	fmt.Println()
	fmt.Println("  # High concurrency with custom corpus")
	fmt.Println("  waf-tester assess -u https://example.com -c 50 -custom-corpus ./my-benign.txt")
	fmt.Println()
}

func printDocsScan() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🔍 SCAN COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The scan command performs deep vulnerability scanning for specific")
	fmt.Println("  vulnerability types with specialized detection logic.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("SCAN TYPES"))
	fmt.Println()
	fmt.Println("  -types <list>        Comma-separated vulnerability types:")
	fmt.Println()
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("sqli"), "SQL Injection - Union, Error, Blind, Time-based")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("xss"), "Cross-Site Scripting - Reflected, Stored, DOM")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("ssrf"), "Server-Side Request Forgery")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("ssti"), "Server-Side Template Injection")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("lfi"), "Local File Inclusion / Path Traversal")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("rce"), "Remote Code Execution / Command Injection")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("oauth"), "OAuth/OIDC misconfigurations")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("xxe"), "XML External Entity")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("jwt"), "JWT token vulnerabilities")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("cors"), "CORS misconfigurations")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("crlf"), "CRLF / HTTP Response Splitting")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("upload"), "File upload vulnerabilities")
	fmt.Printf("  %-12s %s\n", ui.StatValueStyle.Render("nosql"), "NoSQL Injection (MongoDB, etc.)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Scan for SQL injection")
	fmt.Println("  waf-tester scan -u https://target.com -types sqli")
	fmt.Println()
	fmt.Println("  # Multiple vulnerability types")
	fmt.Println("  waf-tester scan -u https://target.com -types sqli,xss,ssrf")
	fmt.Println()
	fmt.Println("  # From target list")
	fmt.Println("  waf-tester scan -l targets.txt -types oauth,jwt")
	fmt.Println()
}

func printDocsMutation() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🔀 MUTATION ENGINE - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The mutation engine transforms payloads to bypass WAF filters.")
	fmt.Println("  It applies encodings, injection locations, and evasion techniques.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("MUTATION MODES"))
	fmt.Println()
	fmt.Println("  -mutation <mode>     Mutation intensity:")
	fmt.Println()
	fmt.Println("  " + ui.StatValueStyle.Render("none") + "      No mutations (raw payloads only)")
	fmt.Println("  " + ui.StatValueStyle.Render("quick") + "     Basic URL encoding")
	fmt.Println("  " + ui.StatValueStyle.Render("standard") + "  Common encodings + locations")
	fmt.Println("  " + ui.StatValueStyle.Render("full") + "      All encoders × all locations × all evasions")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("ENCODERS"))
	fmt.Println()
	fmt.Println("  Transform how payloads are represented:")
	fmt.Println()
	fmt.Println("  url           %27%20OR%201=1")
	fmt.Println("  double_url    %2527%2520OR%25201%253D1")
	fmt.Println("  html_hex      &#x27;&#x20;OR&#x20;1=1")
	fmt.Println("  html_dec      &#39;&#32;OR&#32;1=1")
	fmt.Println("  unicode       \\u0027\\u0020OR\\u00201=1")
	fmt.Println("  base64        JyBPUiAxPTE=")
	fmt.Println("  hex           0x2720204f522031e3d31")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("INJECTION LOCATIONS"))
	fmt.Println()
	fmt.Println("  Where payloads are inserted:")
	fmt.Println()
	fmt.Println("  query_param   ?param=PAYLOAD")
	fmt.Println("  post_form     param=PAYLOAD (application/x-www-form-urlencoded)")
	fmt.Println("  post_json     {\"param\": \"PAYLOAD\"}")
	fmt.Println("  post_xml      <param>PAYLOAD</param>")
	fmt.Println("  header        X-Custom: PAYLOAD")
	fmt.Println("  cookie        Cookie: session=PAYLOAD")
	fmt.Println("  path          /api/PAYLOAD/endpoint")
	fmt.Println("  fragment      #PAYLOAD")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EVASION TECHNIQUES"))
	fmt.Println()
	fmt.Println("  Bypass WAF pattern matching:")
	fmt.Println()
	fmt.Println("  case_swap     SeLeCt, UNION, uNiOn")
	fmt.Println("  sql_comment   SEL/**/ECT, UN/**/ION")
	fmt.Println("  null_byte     SEL[NUL]ECT, pay[NUL]load")
	fmt.Println("  whitespace    SELECT\\t*\\nFROM")
	fmt.Println("  concat        CONC||AT, CON+CAT")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("CHAINING"))
	fmt.Println()
	fmt.Println("  -chain           Enable chained mutations")
	fmt.Println("  -max-chain <n>   Maximum chain depth (default: 2)")
	fmt.Println()
	fmt.Println("  Chaining applies multiple transformations:")
	fmt.Println("  payload " + ui.Icon("→", "->") + " url_encode " + ui.Icon("→", "->") + " case_swap " + ui.Icon("→", "->") + " sql_comment")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Basic mutation")
	fmt.Println("  waf-tester mutate -u https://target.com -mutation standard")
	fmt.Println()
	fmt.Println("  # Full mutation matrix")
	fmt.Println("  waf-tester mutate -u https://target.com -mutation full -chain")
	fmt.Println()
	fmt.Println("  # Specific encoders only")
	fmt.Println("  waf-tester run -u https://target.com -encoders url,double_url,unicode")
	fmt.Println()
}

func printDocsBypass() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🎯 WAF BYPASS FINDER - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The bypass command hunts for WAF bypasses using the full mutation matrix.")
	fmt.Println("  It systematically tests encoding and evasion combinations.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("HOW IT WORKS"))
	fmt.Println()
	fmt.Println("  1. Sends baseline request to detect normal blocking")
	fmt.Println("  2. Iterates through encoder × location × evasion combinations")
	fmt.Println("  3. Identifies which mutations bypass the WAF")
	fmt.Println("  4. Reports successful bypasses with full details")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("BYPASS STRATEGIES"))
	fmt.Println()
	fmt.Println("  " + ui.Icon("•", "-") + " Double encoding: WAF decodes once, backend decodes twice")
	fmt.Println("  " + ui.Icon("•", "-") + " Unicode normalization: Homoglyph substitution")
	fmt.Println("  " + ui.Icon("•", "-") + " Case variations: WAFs often match lowercase only")
	fmt.Println("  " + ui.Icon("•", "-") + " Comment insertion: Break up keywords")
	fmt.Println("  " + ui.Icon("•", "-") + " Protocol-level: HTTP/2, chunked encoding")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Hunt for SQL injection bypasses")
	fmt.Println("  waf-tester bypass -u https://target.com -category sqli")
	fmt.Println()
	fmt.Println("  # With specific payload")
	fmt.Println("  waf-tester bypass -u https://target.com -payload \"' OR 1=1--\"")
	fmt.Println()
	fmt.Println("  # Full mutation matrix")
	fmt.Println("  waf-tester bypass -u https://target.com -mutation full")
	fmt.Println()
}

func printDocsFuzz() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📂 FUZZ COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The fuzz command performs directory and content discovery")
	fmt.Println("  similar to ffuf/gobuster but with WAF-aware capabilities.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FUZZ KEYWORD"))
	fmt.Println()
	fmt.Println("  Use FUZZ keyword to mark injection point:")
	fmt.Println()
	fmt.Println("  waf-tester fuzz -u https://target.com/FUZZ -w wordlist.txt")
	fmt.Println("  waf-tester fuzz -u https://target.com/api/FUZZ -w api-endpoints.txt")
	fmt.Println("  waf-tester fuzz -u https://target.com?param=FUZZ -w values.txt")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("BUILT-IN WORDLISTS"))
	fmt.Println()
	fmt.Println("  -w <file|preset>     Wordlist file or built-in preset:")
	fmt.Println()
	fmt.Println("  common        Common directories and files")
	fmt.Println("  api           API endpoints")
	fmt.Println("  backup        Backup file extensions")
	fmt.Println("  config        Configuration files")
	fmt.Println("  git           Git repository files")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Directory discovery")
	fmt.Println("  waf-tester fuzz -u https://target.com/FUZZ -w common")
	fmt.Println()
	fmt.Println("  # API endpoint discovery")
	fmt.Println("  waf-tester fuzz -u https://target.com/api/FUZZ -w api")
	fmt.Println()
	fmt.Println("  # With filtering")
	fmt.Println("  waf-tester fuzz -u https://target.com/FUZZ -w wordlist.txt -fc 404")
	fmt.Println()
}

func printDocsProbe() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🔌 PROBE COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The probe command performs protocol-level detection and fingerprinting.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("DETECTION CAPABILITIES"))
	fmt.Println()
	fmt.Println("  " + ui.Icon("•", "-") + " HTTP/HTTPS availability")
	fmt.Println("  " + ui.Icon("•", "-") + " HTTP/2 support")
	fmt.Println("  " + ui.Icon("•", "-") + " TLS version and cipher suites")
	fmt.Println("  " + ui.Icon("•", "-") + " WAF/CDN detection (Cloudflare, Akamai, AWS WAF, etc.)")
	fmt.Println("  " + ui.Icon("•", "-") + " Server headers and technology")
	fmt.Println("  " + ui.Icon("•", "-") + " Security headers (HSTS, CSP, X-Frame-Options)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Probe single target")
	fmt.Println("  waf-tester probe -u https://target.com")
	fmt.Println()
	fmt.Println("  # Probe multiple targets")
	fmt.Println("  waf-tester probe -l targets.txt -c 50")
	fmt.Println()
	fmt.Println("  # Pipe from other tools")
	fmt.Println("  cat domains.txt | waf-tester probe -stdin")
	fmt.Println()
}

func printDocsCrawl() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🕷️ CRAWL COMMAND - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The crawl command performs advanced web crawling with scope control.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("SCOPE CONTROL"))
	fmt.Println()
	fmt.Println("  -scope <mode>        Crawling scope:")
	fmt.Println()
	fmt.Println("  strict       Same domain only")
	fmt.Println("  subdomain    Include subdomains")
	fmt.Println("  relaxed      Any link found")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OPTIONS"))
	fmt.Println()
	fmt.Println("  -depth <n>           Maximum crawl depth (default: 3)")
	fmt.Println("  -concurrency <n>     Parallel crawlers (default: 5)")
	fmt.Println("  -timeout <sec>       Request timeout (default: 10)")
	fmt.Println("  -exclude <pattern>   Exclude URLs matching pattern")
	fmt.Println("  -include <pattern>   Only include URLs matching pattern")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Basic crawl")
	fmt.Println("  waf-tester crawl -u https://target.com -depth 5")
	fmt.Println()
	fmt.Println("  # Crawl with subdomain scope")
	fmt.Println("  waf-tester crawl -u https://target.com -scope subdomain")
	fmt.Println()
	fmt.Println("  # Exclude static assets")
	fmt.Println("  waf-tester crawl -u https://target.com -exclude \"\\.(css|js|png|jpg)$\"")
	fmt.Println()
}

func printDocsAnalyze() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📜 ANALYZE (JAVASCRIPT) - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The analyze command performs deep JavaScript static analysis.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("DETECTION CAPABILITIES"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("API Endpoints:"))
	fmt.Println("  " + ui.Icon("•", "-") + " fetch() calls with URL extraction")
	fmt.Println("  " + ui.Icon("•", "-") + " axios requests")
	fmt.Println("  " + ui.Icon("•", "-") + " jQuery.ajax() calls")
	fmt.Println("  " + ui.Icon("•", "-") + " XMLHttpRequest usage")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("HTTP Method Inference:"))
	fmt.Println("  " + ui.Icon("•", "-") + " URL patterns: /login " + ui.Icon("→", "->") + " POST, /delete " + ui.Icon("→", "->") + " DELETE")
	fmt.Println("  " + ui.Icon("•", "-") + " Code context: method: 'POST', type: 'PUT'")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Secret Detection:"))
	fmt.Println("  " + ui.Icon("•", "-") + " AWS Access Keys (AKIA...)")
	fmt.Println("  " + ui.Icon("•", "-") + " Google API Keys")
	fmt.Println("  " + ui.Icon("•", "-") + " GitHub Tokens")
	fmt.Println("  " + ui.Icon("•", "-") + " Stripe Keys")
	fmt.Println("  " + ui.Icon("•", "-") + " Twilio Tokens")
	fmt.Println("  " + ui.Icon("•", "-") + " Generic API Keys and tokens")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("DOM XSS Sinks:"))
	fmt.Println("  " + ui.Icon("•", "-") + " innerHTML assignments")
	fmt.Println("  " + ui.Icon("•", "-") + " document.write()")
	fmt.Println("  " + ui.Icon("•", "-") + " eval()")
	fmt.Println("  " + ui.Icon("•", "-") + " setTimeout/setInterval with strings")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Analyze target JavaScript")
	fmt.Println("  waf-tester analyze -u https://target.com")
	fmt.Println()
	fmt.Println("  # Analyze specific JS file")
	fmt.Println("  waf-tester analyze -f app.bundle.js")
	fmt.Println()
	fmt.Println("  # Verbose output with all findings")
	fmt.Println("  waf-tester analyze -u https://target.com -verbose")
	fmt.Println()
}

func printDocsPayloads() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("💉 PAYLOAD STRUCTURE - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  Payloads are organized by category in JSON files.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("DIRECTORY STRUCTURE"))
	fmt.Println()
	fmt.Println("  payloads/")
	fmt.Println("  ├── injection/")
	fmt.Println("  │   ├── sqli.json")
	fmt.Println("  │   ├── nosqli.json")
	fmt.Println("  │   └── cmdi.json")
	fmt.Println("  ├── xss/")
	fmt.Println("  │   ├── reflected.json")
	fmt.Println("  │   └── stored.json")
	fmt.Println("  ├── auth/")
	fmt.Println("  │   ├── brute.json")
	fmt.Println("  │   └── bypass.json")
	fmt.Println("  └── traversal/")
	fmt.Println("      └── path.json")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("PAYLOAD JSON FORMAT"))
	fmt.Println()
	fmt.Println("  {")
	fmt.Println("    \"payloads\": [")
	fmt.Println("      {")
	fmt.Println("        \"id\": \"sqli-001\",")
	fmt.Println("        \"payload\": \"' OR 1=1--\",")
	fmt.Println("        \"category\": \"injection\",")
	fmt.Println("        \"subcategory\": \"sqli\",")
	fmt.Println("        \"severity\": \"Critical\",")
	fmt.Println("        \"description\": \"Classic SQL injection\",")
	fmt.Println("        \"expected_status\": [200, 302],")
	fmt.Println("        \"expected_match\": \"error|sql|syntax\"")
	fmt.Println("      }")
	fmt.Println("    ]")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("UPDATING PAYLOADS"))
	fmt.Println()
	fmt.Println("  # Fetch latest from OWASP sources")
	fmt.Println("  waf-tester update")
	fmt.Println()
	fmt.Println("  # Validate payload files")
	fmt.Println("  waf-tester validate -payloads ./payloads")
	fmt.Println()
}

func printDocsCategories() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📋 ATTACK CATEGORIES - DETAILED DOCUMENTATION")))
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("injection") + " - Code Injection Attacks")
	fmt.Println("    sqli       SQL Injection (MySQL, PostgreSQL, MSSQL, Oracle)")
	fmt.Println("    nosqli     NoSQL Injection (MongoDB, CouchDB)")
	fmt.Println("    cmdi       Command Injection (OS command execution)")
	fmt.Println("    ldapi      LDAP Injection")
	fmt.Println("    xpath      XPath Injection")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("xss") + " - Cross-Site Scripting")
	fmt.Println("    reflected  Reflected XSS (in URL parameters)")
	fmt.Println("    stored     Stored/Persistent XSS")
	fmt.Println("    dom        DOM-based XSS")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("auth") + " - Authentication Attacks")
	fmt.Println("    brute      Brute force / credential stuffing")
	fmt.Println("    bypass     Authentication bypass")
	fmt.Println("    session    Session fixation/hijacking")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("traversal") + " - Path Traversal / LFI")
	fmt.Println("    lfi        Local File Inclusion")
	fmt.Println("    rfi        Remote File Inclusion")
	fmt.Println("    path       Directory traversal (../, etc.)")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("ssrf") + " - Server-Side Request Forgery")
	fmt.Println("    internal   Access internal services")
	fmt.Println("    cloud      Cloud metadata endpoints")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("ssti") + " - Server-Side Template Injection")
	fmt.Println("    jinja      Jinja2 (Python)")
	fmt.Println("    twig       Twig (PHP)")
	fmt.Println("    freemarker FreeMarker (Java)")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("xxe") + " - XML External Entity")
	fmt.Println("    file       File disclosure")
	fmt.Println("    ssrf       SSRF via XXE")
	fmt.Println("    dos        Billion laughs attack")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Other Categories:"))
	fmt.Println("    cors       CORS misconfiguration")
	fmt.Println("    crlf       HTTP response splitting")
	fmt.Println("    redirect   Open redirect")
	fmt.Println("    upload     File upload vulnerabilities")
	fmt.Println("    jwt        JWT token attacks")
	fmt.Println("    oauth      OAuth/OIDC vulnerabilities")
	fmt.Println("    prototype  Prototype pollution")
	fmt.Println("    deserialize Insecure deserialization")
	fmt.Println()
}

func printDocsOutput() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📊 OUTPUT FORMATS - DETAILED DOCUMENTATION")))
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("console") + " (default)")
	fmt.Println("    Human-readable terminal output with colors")
	fmt.Println("    Best for: Interactive testing, debugging")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("json"))
	fmt.Println("    Single JSON array with all results")
	fmt.Println("    Best for: API integration, detailed analysis")
	fmt.Println("    waf-tester run ... -format json -o results.json")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("jsonl"))
	fmt.Println("    JSON Lines - one JSON object per line")
	fmt.Println("    Best for: Streaming, log aggregation, large result sets")
	fmt.Println("    waf-tester run ... -j -o results.jsonl")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("sarif"))
	fmt.Println("    Static Analysis Results Interchange Format")
	fmt.Println("    Best for: IDE integration, CI/CD pipelines, GitHub Security")
	fmt.Println("    waf-tester run ... -format sarif -o results.sarif")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("csv"))
	fmt.Println("    Comma-separated values")
	fmt.Println("    Best for: Spreadsheet analysis, reporting")
	fmt.Println("    waf-tester run ... -format csv -o results.csv")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("md"))
	fmt.Println("    Markdown table")
	fmt.Println("    Best for: Documentation, README files")
	fmt.Println("    waf-tester run ... -format md -o results.md")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("html"))
	fmt.Println("    Interactive HTML report with filtering")
	fmt.Println("    Best for: Sharing with stakeholders, archiving")
	fmt.Println("    waf-tester run ... -format html -o report.html")
	fmt.Println()
}

func printDocsExamples() {
	fmt.Println(ui.SectionStyle.Render(ui.Sanitizef("%s REAL-WORLD EXAMPLES", ui.Icon("💡", "*"))))
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("1. Complete Security Assessment"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  # Discover target")
	fmt.Println("  waf-tester discover -u https://app.company.com -output discovery.json")
	fmt.Println()
	fmt.Println("  # Generate test plan")
	fmt.Println("  waf-tester learn -discovery discovery.json -output testplan.json")
	fmt.Println()
	fmt.Println("  # Run tests with HTML report")
	fmt.Println("  waf-tester run -plan testplan.json -format html -o report.html")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("2. Quick SQL Injection Test"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  waf-tester run -u https://target.com/search?q=test -category sqli -ac")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("3. WAF Bypass Hunting"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  # Low and slow to avoid detection")
	fmt.Println("  waf-tester bypass -u https://target.com -category xss \\")
	fmt.Println("    -mutation full -c 5 -rl 10 -realistic")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("4. CI/CD Integration"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  # Generate SARIF for GitHub Security")
	fmt.Println("  waf-tester run -u $TARGET_URL -plan testplan.json \\")
	fmt.Println("    -format sarif -o results.sarif -s")
	fmt.Println()
	fmt.Println("  # Exit code: 0 = no findings, 1 = findings detected")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("5. Multi-Target Scanning"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  # From file")
	fmt.Println("  waf-tester probe -l targets.txt -c 50 -o live-hosts.txt")
	fmt.Println("  waf-tester scan -l live-hosts.txt -types sqli,xss")
	fmt.Println()
	fmt.Println("  # From stdin (pipe from other tools)")
	fmt.Println("  subfinder -d target.com | waf-tester probe -stdin")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("6. Authenticated Testing"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  waf-tester run -u https://target.com -plan testplan.json \\")
	fmt.Println("    -H \"Authorization: Bearer eyJ...\" \\")
	fmt.Println("    -H \"Cookie: session=abc123\"")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("7. Through Proxy (Burp Suite)"))
	fmt.Println("  ─────────────────────────────────")
	fmt.Println("  waf-tester run -u https://target.com -plan testplan.json \\")
	fmt.Println("    -x http://127.0.0.1:8080 -k")
	fmt.Println()
}

func printDocsMcp() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🤖 MCP SERVER - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  The mcp command starts a Model Context Protocol (MCP) server that")
	fmt.Println("  exposes waf-tester capabilities to AI assistants like Claude, VS Code")
	fmt.Println("  Copilot, and other MCP-compatible clients.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("TRANSPORT MODES"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("stdio (default)"))
	fmt.Println("    Communicates over stdin/stdout. Used by IDE integrations.")
	fmt.Println("    waf-tester mcp --stdio")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("HTTP (Streamable HTTP)"))
	fmt.Println("    Starts an HTTP server with SSE streaming. Used for remote/Docker.")
	fmt.Println("    waf-tester mcp --http :8080")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("MCP TOOLS (AI-callable)"))
	fmt.Println()
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("list_payloads"), "Browse and filter payload catalog by category/severity")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("detect_waf"), "Detect WAF vendor on a target URL with progress streaming")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("scan"), "Run security scan against a target (category, severity filters)")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("mutate"), "Apply WAF-bypass encodings to a payload string")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("discover"), "Map attack surface (endpoints, params, tech stack)")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("learn"), "Generate targeted test plan from discovery results")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("assess"), "Enterprise assessment with F1/precision/MCC metrics")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("bypass"), "Systematic bypass discovery with mutation matrix")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("probe"), "TLS/HTTP probing and WAF/CDN fingerprinting")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("generate_cicd"), "Generate CI/CD pipeline for WAF testing")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("MCP RESOURCES"))
	fmt.Println()
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://version"), "Server version and capabilities")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://payloads"), "Full payload catalog with categories")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://payloads/{cat}"), "Payloads filtered by category")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://guide"), "WAF testing methodology guide")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://waf-signatures"), "WAF vendor signatures and bypass tips")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://evasion-techniques"), "Evasion technique catalog")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://owasp-mappings"), "OWASP Top 10 category mappings")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://config"), "Configuration defaults and bounds")
	fmt.Printf("  %-30s %s\n", ui.StatValueStyle.Render("waftester://templates"), "Template library catalog (41 templates)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("MCP PROMPTS"))
	fmt.Println()
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("security_audit"), "Guided 5-phase security assessment workflow")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("waf_bypass"), "6-step WAF bypass discovery strategy")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("full_assessment"), "Enterprise assessment with compliance mapping")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("discovery"), "Guided discovery and attack surface mapping")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("evasion_research"), "Deep evasion technique research")
	fmt.Printf("  %-18s %s\n", ui.StatValueStyle.Render("template_scan"), "Template-based WAF testing workflow")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("FLAGS"))
	fmt.Println()
	fmt.Println("  --stdio            Use stdin/stdout transport (default)")
	fmt.Println("  --http <addr>      Start HTTP server at address (e.g., :8080)")
	fmt.Println("  --payloads <dir>   Payload directory (default: ./payloads)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("IDE INTEGRATION"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("VS Code (mcp.json):"))
	fmt.Println("    {")
	fmt.Println("      \"servers\": {")
	fmt.Println("        \"waf-tester\": {")
	fmt.Println("          \"command\": \"waf-tester\",")
	fmt.Println("          \"args\": [\"mcp\", \"--stdio\"]")
	fmt.Println("        }")
	fmt.Println("      }")
	fmt.Println("    }")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Claude Desktop (claude_desktop_config.json):"))
	fmt.Println("    {")
	fmt.Println("      \"mcpServers\": {")
	fmt.Println("        \"waf-tester\": {")
	fmt.Println("          \"command\": \"waf-tester\",")
	fmt.Println("          \"args\": [\"mcp\", \"--stdio\"]")
	fmt.Println("        }")
	fmt.Println("      }")
	fmt.Println("    }")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("LIVE STREAMING"))
	fmt.Println()
	fmt.Println("  The MCP server streams progress during long-running operations:")
	fmt.Println("  " + ui.Icon("•", "-") + " WAF detection: reports each detection technique as it runs")
	fmt.Println("  " + ui.Icon("•", "-") + " Scanning: streams per-payload results with bypass notifications")
	fmt.Println("  " + ui.Icon("•", "-") + " All tools report progress via MCP progress notifications")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("EXAMPLES"))
	fmt.Println()
	fmt.Println("  # Start stdio server (for IDE integration)")
	fmt.Println("  waf-tester mcp")
	fmt.Println()
	fmt.Println("  # Start HTTP server on port 8080")
	fmt.Println("  waf-tester mcp --http :8080")
	fmt.Println()
	fmt.Println("  # With custom payload directory")
	fmt.Println("  waf-tester mcp --payloads /opt/payloads")
	fmt.Println()
}

func printDocsWorkflow() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("🔄 RECOMMENDED WORKFLOWS")))
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 1: Full Assessment (Recommended)"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  ┌─────────────┐    ┌─────────────┐    ┌─────────────┐")
	fmt.Println("  │  discover   │ -> │    learn    │ -> │     run     │")
	fmt.Println("  │ (find URLs) │    │ (make plan) │    │ (test it)   │")
	fmt.Println("  └─────────────┘    └─────────────┘    └─────────────┘")
	fmt.Println()
	fmt.Println("  Best for: Complete security assessments, new targets")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 2: Quick Test"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  ┌──────────────────────────────────────────┐")
	fmt.Println("  │  waf-tester run -u URL -category sqli   │")
	fmt.Println("  └──────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Best for: Quick tests, known endpoints")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 3: Automated (One Command)"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  ┌──────────────────────────────────────────┐")
	fmt.Println("  │  waf-tester auto -u URL -service app    │")
	fmt.Println("  └──────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("  Best for: CI/CD, scheduled scans, quick assessments")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 4: WAF Bypass Research"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  ┌─────────────┐    ┌─────────────┐    ┌─────────────┐")
	fmt.Println("  │   probe     │ -> │   bypass    │ -> │   mutate    │")
	fmt.Println("  │ (detect WAF)│    │ (find holes)│    │(full matrix)│")
	fmt.Println("  └─────────────┘    └─────────────┘    └─────────────┘")
	fmt.Println()
	fmt.Println("  Best for: WAF testing, bypass research")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 5: Bug Bounty Recon"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  subfinder -d target.com | waf-tester probe -stdin > live.txt")
	fmt.Println("  waf-tester discover -l live.txt -output discovery.json")
	fmt.Println("  waf-tester learn -discovery discovery.json -output plan.json")
	fmt.Println("  waf-tester run -plan plan.json -realistic -ac -format sarif")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 6: Template-Based Scan"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  waf-tester template -t templates/nuclei/http/waf-bypass/ -u https://target.com")
	fmt.Println("  waf-tester template -t templates/nuclei/http/waf-detection/ -u https://target.com")
	fmt.Println()
	fmt.Println("  Best for: Nuclei-compatible template scanning, reproducible tests")
	fmt.Println()

	fmt.Println("  " + ui.SubtitleStyle.Render("Workflow 7: Policy-Enforced CI/CD Gate"))
	fmt.Println("  ─────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  waf-tester workflow -f templates/workflows/ci-gate.yaml \\")
	fmt.Println("    -var target=https://target.com \\")
	fmt.Println("    -var policy=templates/policies/strict.yaml")
	fmt.Println()
	fmt.Println("  Best for: CI gates, compliance enforcement, automated reporting")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("BUNDLED TEMPLATE FILES"))
	fmt.Println()
	fmt.Println("  Run 'waf-tester docs templates' for complete template documentation.")
	fmt.Println("  Available template directories:")
	fmt.Println("    templates/nuclei/http/waf-bypass/      11 bypass templates")
	fmt.Println("    templates/nuclei/http/waf-detection/    5 detection templates")
	fmt.Println("    templates/workflows/                    5 workflow templates")
	fmt.Println("    templates/policies/                     5 policy templates")
	fmt.Println("    templates/overrides/                    3 override configs")
	fmt.Println("    templates/output/                       6 output templates")
	fmt.Println("    templates/report-configs/               5 report configs")
	fmt.Println()
}

func printDocsTemplates() {
	fmt.Println(ui.SectionStyle.Render(ui.SanitizeString("📋 TEMPLATE LIBRARY - DETAILED DOCUMENTATION")))
	fmt.Println()
	fmt.Println("  WAF Tester ships with 41 ready-to-use templates across 6 categories.")
	fmt.Println("  Templates are installed at templates/ and shipped in Docker/releases.")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("NUCLEI BYPASS TEMPLATES (11)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/nuclei/http/waf-bypass/"))
	fmt.Println("    sqli-basic.yaml       SQL injection (UNION, error, blind, time-based)")
	fmt.Println("    sqli-evasion.yaml     SQLi WAF evasion (comments, encoding, HPP)")
	fmt.Println("    xss-basic.yaml        Cross-site scripting (script tags, events, SVG)")
	fmt.Println("    xss-evasion.yaml      XSS WAF evasion (entity encoding, bracket notation)")
	fmt.Println("    ssrf-bypass.yaml      SSRF clouds metadata + IP tricks")
	fmt.Println("    lfi-bypass.yaml       LFI with UTF-8, PHP wrappers, glob patterns")
	fmt.Println("    rce-bypass.yaml       RCE with IFS, wildcards, newline injection")
	fmt.Println("    ssti-bypass.yaml      SSTI multi-engine (Jinja2, Twig, ERB, Velocity)")
	fmt.Println("    xxe-bypass.yaml       XXE with OOB, XInclude, SVG injection")
	fmt.Println("    crlf-bypass.yaml      CRLF with Unicode, response splitting")
	fmt.Println("    nosqli-bypass.yaml    NoSQL injection (MongoDB operators, $where)")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Usage:"))
	fmt.Println("    waf-tester template -t templates/nuclei/http/waf-bypass/ -u https://target.com")
	fmt.Println("    waf-tester template -t templates/nuclei/http/waf-bypass/sqli-basic.yaml -u https://target.com")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("NUCLEI DETECTION TEMPLATES (5)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/nuclei/http/waf-detection/"))
	fmt.Println("    cloudflare-detect.yaml     Cloudflare WAF (CF-Ray, headers, cookies)")
	fmt.Println("    aws-waf-detect.yaml        AWS WAF/CloudFront (x-amzn headers)")
	fmt.Println("    akamai-detect.yaml         Akamai Kona (GHost, Reference ID)")
	fmt.Println("    azure-waf-detect.yaml      Azure WAF/Application Gateway")
	fmt.Println("    modsecurity-detect.yaml    ModSecurity/CRS (version + rule extractors)")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("WORKFLOW TEMPLATES (5)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/workflows/"))
	fmt.Println("    full-scan.yaml        Complete scan with fingerprint, calibrate, triple report")
	fmt.Println("    quick-probe.yaml      Fast probe - critical+high severity only")
	fmt.Println("    waf-detection.yaml    WAF fingerprinting workflow")
	fmt.Println("    api-scan.yaml         API-focused with OpenAPI spec support")
	fmt.Println("    ci-gate.yaml          CI/CD gate with SARIF+JUnit and policy enforcement")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Usage:"))
	fmt.Println("    waf-tester workflow -f templates/workflows/full-scan.yaml -var target=https://target.com")
	fmt.Println("    waf-tester workflow -f templates/workflows/ci-gate.yaml -var target=https://target.com")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("POLICY TEMPLATES (5)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/policies/"))
	fmt.Println("    strict.yaml           95% effectiveness floor, 28 bypass categories")
	fmt.Println("    standard.yaml         85% effectiveness, balanced for production")
	fmt.Println("    permissive.yaml       50% effectiveness, development-friendly")
	fmt.Println("    owasp-top10.yaml      OWASP Top 10 2021 category mapping")
	fmt.Println("    pci-dss.yaml          PCI DSS v4.0 requirements (6.2.4, 6.4.1, etc.)")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Usage:"))
	fmt.Println("    waf-tester scan -u https://target.com --policy templates/policies/strict.yaml")
	fmt.Println("    waf-tester auto -u https://target.com --policy templates/policies/pci-dss.yaml")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OVERRIDE TEMPLATES (3)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/overrides/"))
	fmt.Println("    api-only.yaml                  API testing (JSON, no browser attacks)")
	fmt.Println("    crs-tuning.yaml                ModSecurity CRS paranoia level tuning")
	fmt.Println("    false-positive-suppression.yaml Known FP suppression rules")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Usage:"))
	fmt.Println("    waf-tester scan -u https://api.example.com --overrides templates/overrides/api-only.yaml")
	fmt.Println("    waf-tester auto -u https://target.com --overrides templates/overrides/false-positive-suppression.yaml")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("OUTPUT TEMPLATES (6)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/output/"))
	fmt.Println("    markdown-report.tmpl      Executive summary with severity distribution")
	fmt.Println("    text-summary.tmpl         ASCII console-friendly report")
	fmt.Println("    slack-notification.tmpl   Slack Block Kit JSON notification")
	fmt.Println("    junit.tmpl                JUnit XML for CI/CD integration")
	fmt.Println("    csv.tmpl                  CSV with 12 columns, OWASP/CWE links")
	fmt.Println("    asff.tmpl                 AWS Security Finding Format")
	fmt.Println()

	fmt.Println(ui.SectionStyle.Render("REPORT CONFIGS (5)"))
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Path: templates/report-configs/"))
	fmt.Println("    minimal.yaml          Compact 6-section report")
	fmt.Println("    enterprise.yaml       11 sections with OWASP/PCI/NIST mapping")
	fmt.Println("    compliance.yaml       Regulatory attestation format")
	fmt.Println("    dark.yaml             Modern dark theme, filterable results")
	fmt.Println("    print.yaml            Print-optimized with grayscale charts")
	fmt.Println()
	fmt.Println("  " + ui.SubtitleStyle.Render("Usage:"))
	fmt.Println("    waf-tester scan -u https://target.com --template-config templates/report-configs/enterprise.yaml")
	fmt.Println("    waf-tester auto -u https://target.com --template-config templates/report-configs/dark.yaml")
	fmt.Println()
}
